Image2Attach
============

:author: alswl

What's this
-----------

Image2Attach is a extension for http:moinmo.in[MoinMoin].
It can create a page action to save images from web to page's attachments.

Requirment
----------

* MoinMoin 1.9 (I only test in this version.)

Install
-------

* copy action/* to data/plugin/action/
* edit MoinMoin/theme/__init__.py
* restart python server

----
menu = [
	'raw',
	'print',
	'RenderAsDocbook',
	'Image2Attach', # <- add here

titles = {
	# action: menu title
	'__title__': _("More Actions:", formatted=False),
	# Translation may need longer or shorter separator
	'__separator__': _('------------', formatted=False),
	'raw': _('Raw Text', formatted=False),
	'print': _('Print View', formatted=False),
	'refresh': _('Delete Cache', formatted=False),
	'SpellCheck': _('Check Spelling', formatted=False), # rename action!
	'RenamePage': _('Rename Page', formatted=False),
	'DeletePage': _('Delete Page', formatted=False),
	'LikePages': _('Like Pages', formatted=False),
	'LocalSiteMap': _('Local Site Map', formatted=False),
	'MyPages': _('My Pages', formatted=False),
	'SubscribeUser': _('Subscribe User', formatted=False),
	'Despam': _('Remove Spam', formatted=False),
	'PackagePages': _('Package Pages', formatted=False),
	'RenderAsDocbook': _('Render as Docbook', formatted=False),
	'Image2Attach': _('Image2Attach'), # <- add here
	}
----

Usage
-----

Go into a page, click `more action` - `Image2Attach` .
It will take a while to fetch the images,
after that it will save the image to attachments and replace the
image's link with attachment's link.
Finnally it will commit a change with message
\'internet image save to attachment' to wiki.

Enjoy it, any bugs can report to https://github.com/alswl/image2attach/issues[
Issue Report].

Links
-----

You can get some develop infomation in http://log4d.com/tag/image2attach .

// vim: set ft=asciidoc:
